### ISSUE TITLE
Add support for Guzzle 7

### ISSUE THREAD

**Issue by bencroker** [craftcms/commerce-omnipay#15]
Craft 3.6 will support Guzzle 7, however Commerce Omnipay requires `php-http/guzzle6-adapter` which is locked to Guzzle 6. It seems like removing the `php-http/guzzle6-adapter` dependency would prevent future issues from arising.
https://github.com/craftcms/commerce-omnipay/blob/2.1.1/composer.json#L28

**Comment by lukeholder** [comment]
Hi @bencroker 

We are currently working on Commerce 3.3 that will be our official 3.6 support release. We will then upgrade `commerce-omnipay` to guzzle 7 at that point.

In Craft core, we updated Guzzle to 7.x, for projects that don’t have any plugins that require Guzzle 6. Guzzle 6 still though.

It looks like we provided a guzzle 6 adapter to omnipay in`commerce-omnipay`, but didn't require guzzle 6 directly since we relied on craft requiring guzzle 6. 

You can force guzzle 6 to work with the current `commerce-omnipay` package by adding this to your project's composer.json required packages:

```
 "guzzlehttp/guzzle": "^6.5.5",
```

(You could alternatively add this requirement a custom gateway plugin).

Doing this should force guzzle 6 and keep everything working.

The next version of the `commerce-omnipay` will require Commerce 3.3 and use guzzle 7. When you upgrade to that, you can remove the guzzle 6 requirement from your project or plugin.

Hope that helps.

-Luke

**Comment by bencroker** [comment]
Thanks Luke!
